### ISSUE TITLE
CSV 64 bit error

### ISSUE THREAD

**Issue by JitGub** [tyrasd/overpass-turbo#264] opened 2016-09-22 22:32 UTC
Hi

When I use xml it is ok.
When I use csv there is an error.

When I do this I get the correct node.

    [out:xml];(node["addr:country"="DK"]["addr:postcode"="1699"]["addr:housenumber"="30A"];);out meta;

```xml
<?xml version="1.0" encoding="UTF-8"?>
<osm version="0.6" generator="Overpass API">
<note>The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.</note>
<meta osm_base="2016-09-22T22:01:02Z"/>

  <node id="4332562999" lat="55.6680240" lon="12.5627220" version="1" timestamp="2016-08-02T16:20:53Z" changeset="41195884" 

uid="2184056" user="AWSbot">
    <tag k="addr:city" v="København V"/>
    <tag k="addr:country" v="DK"/>
    <tag k="addr:housenumber" v="30A"/>
    <tag k="addr:postcode" v="1699"/>
    <tag k="addr:street" v="Staldgade"/>
    <tag k="osak:identifier" v="ed65081a3245486fa1425db2ab506d49"/>
    <tag k="osak:municipality_no" v="101"/>
    <tag k="osak:revision" v="2016-08-02T10:37:13.327"/>
    <tag k="osak:street" v="Staldgade"/>
    <tag k="osak:street_no" v="6814"/>
    <tag k="source" v="Geodatastyrelsens Adresse Web Services (AWS)"/>
  </node>

</osm>
```

When I do this I get the wrong node.

```
[out:csv(::"id", ::"lat", ::"lon", ::"version", ::"timestamp", ::"changeset", ::"uid", ::"user", "addr:city", "addr:country","addr:housename", "addr:housenumber", "addr:postcode", "addr:street", "source";true;"\t")];(node["addr:country"="DK"]["addr:postcode"="1699"]["addr:housenumber"="30A"];);out meta;
```

```
@id	@lat	@lon	@version	@timestamp	@changeset	@uid	@user	addr:city	addr:country	addr:housename	addr:housenumber	addr:postcode	addr:street	addr:door	addr:floor	osak:house_no	osak:identifier	osak:municipality_name	osak:municipality_no	osak:revision	osak:street	osak:street_name	osak:street_no	osak:subdivision	osak:fixme	ois:fixme	fixme	fvst:fixme	note	comment	name	kms:last_updated	kms:county_no	kms:county_name	kms:municipality_name	kms:municipality_no	kms:zip_name	kms:zip_code	kms:street_name	kms:street_no	kms:house_no	source
37595703	55.6680240	12.5627220	1	2016-08-02T16:20:53Z	41195884	2184056	AWSbot	København V	DK		30A	1699	Staldgade				ed65081a3245486fa1425db2ab506d49		101	2016-08-02T10:37:13.327	Staldgade		6814																			Geodatastyrelsens Adresse Web Services (AWS)
```

**Comment by tyrasd** [comment] 2016-09-23 10:27
I think this is a duplicate of https://github.com/drolbr/Overpass-API/issues/304. @mmd: Is that right?

**Closed by tyrasd** 2016-09-23 10:27 UTC
Labels: Overpass-API

**Comment by mmd-osm** [comment] 2016-12-05 21:30
Yes, it's a duplicate of that issue.
