### ISSUE TITLE
"This query returned quite a lot of data" threshold

### ISSUE THREAD

**Issue by Dimitar5555** [tyrasd/overpass-turbo#701] opened 2024-06-24 10:23 UTC
Currently it looks like "quite a lot of data" is defined as 2MB or more. Is it possible to change that threshold? Potentially even have a local setting which allows the user to change it?

**Comment by danieldegroot2** [comment] 2024-07-13 10:44
Duplicate of #248

**Closed** 2024-07-13 10:56 UTC
