### ISSUE TITLE
Support greater-than, less-than, etc

### ISSUE THREAD

**Issue by naoliv** [tyrasd/overpass-turbo#223] opened 2016-02-05 17:17 UTC
Could overpass-turbo support greater-than, less-than, etc?
For example, if an user would like to have every highway with more than 3 lanes, he could use something like `[lanes > 3]`.

It should support `>`, `>=`, `<` and `<=`, if possible.

**Comment by tyrasd** [comment] 2016-02-07 15:32
duplicate of https://github.com/drolbr/Overpass-API/issues/78. see also https://github.com/tyrasd/overpass-turbo/issues/143

**Closed by tyrasd** 2016-02-07 15:32 UTC
Labels: Overpass-API

**Comment by mmd-osm** [comment] 2016-12-05 21:34
See http://gis.19327.n8.nabble.com/Date-ranges-with-Overpass-API-td5886864.html

**Comment by zwillikon** [comment] 2024-10-14 10:19
@mmd-osm Hi, nabble has sadly gone offline.
