### ISSUE TITLE
`"Drinking Water" in London` in Wizard query does not work

### ISSUE THREAD

**Issue by habi** [tyrasd/overpass-turbo#685] opened 2024-02-10 13:18 UTC
Entering `"Drinking Water" in London` into the Query Wizard window at https://overpass-turbo.eu/ fails to complete the search.
Entering `"Drinking Water" in Zürich` also fails to complete the search.

Entering `"Drinking Water" in Zürich` at http://overpass-turbo.osm.ch works just fine.

Safari Version 17.2.1 (19617.1.17.11.12) on macOS 14.2.1 (23C71)

**Comment by habi** [comment] 2024-02-10 13:19
Mentioned on https://redd.it/19dr8yh, tested just now by me

**Comment by hfs** [comment] 2024-02-20 06:58
Duplicate of #667

**Comment by simon04** [comment] 2024-06-12 21:42
Duplicate of #667.

**Closed by simon04** 2024-06-12 21:42 UTC
Labels: bug
