### ISSUE TITLE
Add a "edit here" button

### ISSUE THREAD

**Issue by pietervdvn** [tyrasd/overpass-turbo#358] opened 2018-01-29 14:30 UTC
It would be useful to have an button which redirects to the editor on OSM.org. Then it would be quite easy to fix issues which are highlighted by a query with one click.

**Comment by mmd-osm** [comment] 2018-01-30 17:34
Duplicate of https://github.com/tyrasd/overpass-turbo/issues/144?

**Comment by tyrasd** [comment] 2018-02-01 09:01
yes, thanks for linking the other issue. let's close the duplicate

**Closed by tyrasd** 2018-02-01 09:01 UTC
Labels: usability

**Comment by pietervdvn** [comment] 2018-02-01 18:14
This is indeed a duplicate
Thanks for closing it.
