### ISSUE TITLE
Missing http -> https redirect

### ISSUE THREAD

**Issue by Dimitar5555** [tyrasd/overpass-turbo#684] opened 2024-01-24 16:30 UTC
If you open a fresh version of Firefox with default settings and enter `overpass-turbo.eu`, you will get to the http version of the site. The http->https redirect is missing for some reason.

**Comment by mmd-osm** [comment] 2024-01-25 06:26
Duplicate of #336

**Closed** 2024-01-25 07:42 UTC
