### ISSUE TITLE
Set limit for "large amounts of data" warning (enhancement)

### ISSUE THREAD

**Issue by bjohas** [tyrasd/overpass-turbo#302] opened 2017-05-09 08:24 UTC
The suggestion is to introduce [maxdata:x] that disables the data warning if the data size is below x. The improves usability when running frequent queries that are about 2MB (the current limit).

**Comment by tyrasd** [comment] 2017-05-09 08:27
duplicate of #248

**Closed by tyrasd** 2017-05-09 08:27 UTC
