### ISSUE TITLE
overpass stalls when exporting PNG with manual bounding box

### ISSUE THREAD

**Issue by ebauch** [tyrasd/overpass-turbo#362] opened 2018-02-09 14:52 UTC
Never stops rendering. Already deactivated Ad-Block. Seems to work only sporadically. 

![image](https://user-images.githubusercontent.com/3758223/36033268-887e96f6-0d7e-11e8-84e7-75ba51841afe.png)

**Comment by tyrasd** [comment] 2018-02-10 08:40
duplicate of #351 (it's already fixed in master, but just not deployed on the main instance yet)

**Closed by tyrasd** 2018-02-10 08:40 UTC
