### ISSUE TITLE
Textfeld not editable in mobile Safari and Firefox

### ISSUE THREAD

**Issue by bitnapper** [tyrasd/overpass-turbo#354] opened 2017-12-20 09:30 UTC
In Safari and Firefox on iOS (iPhone or iPad) the textbox cant be edited. Text can be selected but not be changed, added or removed.

**Comment by HolgerJeromin** [comment] 2017-12-20 10:07
Just a note: No other browser is allowed to have its own rendering engine on iOS. So Firefox/Chrome on iOS is quite the same than Safari.

**Comment by tyrasd** [comment] 2017-12-21 10:03
duplicate of #267, see the workaround posted there.

**Closed by tyrasd** 2017-12-21 10:03 UTC
