### ISSUE TITLE
CRITICAL: crosses do not line up with names (overpass-turbo 7883359)

### ISSUE THREAD

**Issue by axd1967** [tyrasd/overpass-turbo#530] opened 2021-08-28 17:09 UTC
This is a SUPER CRITICAL issue because the user is likely to delete the wrong saved query!

Firefox 91.0.2

![image](https://user-images.githubusercontent.com/3529789/131225442-6595e236-3b6f-4087-a086-e9410996d778.png)

to demonstrate the issue, 
1. open the Save dialog (to OSM.org)
2. scroll down 

BUG: observe that the crosses to the right are not synced scrolling.

**Comment by axd1967** [comment] 2021-08-28 17:15
(and no... I did NOT read the dialog asking whether I wanted to deleted "_query XXX_" ! I assume the correct query is deleted when I click the delete (cross) button. I've never seen anywhere such kind of dissociation between label and checkbox.

**Comment by simon04** [comment] 2021-08-29 07:24
Duplicate of #426. Please test/use the latest version https://tyrasd.github.io/overpass-turbo/

**Closed by simon04** 2021-08-29 07:24 UTC

**Comment by axd1967** [comment] 2021-08-29 14:32
thanks.

BUT: this was using https://overpass-turbo.eu/ , so these people should URGENTLY update their copy...

![image](https://user-images.githubusercontent.com/3529789/131254024-ca427377-6da9-4938-be90-bab1ceef6d88.png)

**Comment by axd1967** [comment] 2021-10-31 17:49
Still an issue on https://overpass-turbo.eu/: (and yes, I bet this is not an issue for https://github.com/tyrasd/overpass-turbo/, but something has to be done; users don't care where the most recent version is, all they need is a working site)

![image](https://user-images.githubusercontent.com/3529789/139595444-388fbe62-5e7f-48a2-af35-42f6dba42c2c.png)

![image](https://user-images.githubusercontent.com/3529789/139595465-e6ff4349-ae98-47f6-b6f4-20b8c892b5e2.png)

I don't understand how this is possible?

The "version" on the site above is (still) 7883359 (rather than some SHA1 as I erroneously assumed) - I have no clue with what SHA1 this could correspond on the tyrasd repo.

It looks like https://github.com/tyrasd/overpass-turbo/ is no longer "on speaking terms" with https://overpass-turbo.eu/ ?

It might be handy to introduce a decent versioning scheme (eg SemVer) that is "human-readable".

The problem with the GitHub version is that queries cannot be saved (AFAIK).
