### ISSUE TITLE
Store custom API link in cookies

### ISSUE THREAD

**Issue by mueschel** [tyrasd/overpass-turbo#345] opened 2017-10-29 12:03 UTC
Settings allow to define an own Overpass API to get data from. It would be nice if custom URIs could be stored (e.g. in a cookie). Currently changing forth and back from the official API to an own one requires typing in the custom URI every time, because the drop-down only lists the official APIs.

**Comment by mmd-osm** [comment] 2017-10-29 18:26
Duplicate of https://github.com/tyrasd/overpass-turbo/issues/243#issuecomment-223749618

**Closed** 2018-01-03 18:33 UTC
Labels: enhancement, usability
